name: Feature Request
description: 提交功能建议或产品改进想法 | Submit feature ideas or product improvement suggestions
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议。请尽量说明背景、目标和预期价值，便于我们评估优先级。
        Thanks for your suggestion. Please include the background, goal, and expected value so we can evaluate priority.
  - type: checkboxes
    id: precheck
    attributes:
      label: 提交前检查 | Check Before Submit
      options:
        - label: 我已搜索过现有 Issues，确认不是重复需求 | I have searched existing issues and confirmed this is not a duplicate request
          required: true
  - type: textarea
    id: problem
    attributes:
      label: 需求背景/痛点 | Background / Pain Points
      description: 你遇到了什么问题，为什么需要这个功能 | What problem are you facing, and why is this feature needed?
      placeholder: "例如：当前无法快速批量调整图层透明度，影响效率 | Example: It is currently hard to batch-adjust layer opacity, which hurts workflow efficiency"
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建议方案 | Proposed Solution
      description: 描述你期望的功能行为或交互流程 | Describe the expected behavior or interaction flow
      placeholder: "例如：在图层面板增加多选后统一调整透明度 | Example: Add multi-select in the layer panel and allow unified opacity adjustment"
    validations:
      required: true
  - type: textarea
    id: expected_value
    attributes:
      label: 预期收益 | Expected Value
      description: 这个功能能解决什么问题，带来什么价值 | What problem does this solve, and what value does it bring?
      placeholder: "例如：减少重复操作，提升大项目编辑效率 | Example: Reduce repetitive work and improve editing efficiency in large projects"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案 | Alternatives
      description: 你尝试过的替代方案或折中方式（可选） | Alternative or workaround approaches you have tried (optional)
  - type: textarea
    id: references
    attributes:
      label: 参考资料 | References
      description: 可附上截图、原型、竞品链接或其他说明 | Attach screenshots, mockups, competitor links, or other references

